---
- hosts: undercloud
  vars:
    metadata:
      name: Provide difference in hardware configuration
      description: This test provides difference in configuration based on data collected in ironic-inspector
      require_plan: true
  tasks:
  - name: Run the Discovery diff
    discovery_diff:
