---
- hosts: overcloud
  vars:
    metadata:
      name: Network Configuration
      description: >
        Validations verify that the network was configured properly
        on all nodes
      stage: network-validation
- include: ../validations/compute_node_connectivity.yaml
